// Page size preset types and constants
export type PagePresetDesignUnit = 'Pixel' | 'Millimeter' | 'Inch';

export interface PageSizePreset {
    id: string;
    label: string;
    width: number;
    height: number;
    designUnit: PagePresetDesignUnit;
}

export interface PagePresetGroup {
    id: string;
    title: string;
    presets: PageSizePreset[];
}

export const PAGE_SIZE_PRESET_GROUPS: PagePresetGroup[] = [
    {
        id: 'instagram',
        title: 'Instagram',
        presets: [
            {
                id: 'page-sizes-instagram-square',
                label: 'Square Post (1:1)',
                width: 1080,
                height: 1080,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-instagram-landscape',
                label: 'Landscape Post (1.91:1)',
                width: 1080,
                height: 566,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-instagram-portrait',
                label: 'Portrait Post (4:5)',
                width: 1080,
                height: 1350,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-instagram-story',
                label: 'Story/Reels/IGTV (9:16)',
                width: 1080,
                height: 1920,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-instagram-profile',
                label: 'Instagram Profile Photo',
                width: 320,
                height: 320,
                designUnit: 'Pixel',
            },
        ],
    },
    {
        id: 'facebook',
        title: 'Facebook',
        presets: [
            {
                id: 'page-sizes-facebook-square',
                label: 'Square Post (1:1)',
                width: 1080,
                height: 1080,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-facebook-shared-image',
                label: 'Shared Image (1.91:1)',
                width: 1200,
                height: 630,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-facebook-video-landscape',
                label: 'Video Landscape (16:9)',
                width: 1280,
                height: 720,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-facebook-video-vertical',
                label: 'Video Vertical (9:16)',
                width: 720,
                height: 1280,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-facebook-cover',
                label: 'Cover Photo',
                width: 820,
                height: 312,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-facebook-profile',
                label: 'Profile Photo',
                width: 170,
                height: 170,
                designUnit: 'Pixel',
            },
        ],
    },
    {
        id: 'x',
        title: 'X',
        presets: [
            {
                id: 'page-sizes-x-instream',
                label: 'In-stream Photo (16:9)',
                width: 1200,
                height: 675,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-x-header',
                label: 'Profile Header (3:1)',
                width: 1500,
                height: 500,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-x-video',
                label: 'Video (16:9)',
                width: 1280,
                height: 720,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-x-profile',
                label: 'Profile Photo (1:1)',
                width: 400,
                height: 400,
                designUnit: 'Pixel',
            },
        ],
    },
    {
        id: 'linkedIn',
        title: 'LinkedIn',
        presets: [
            {
                id: 'page-sizes-linkedin-shared-post',
                label: 'Shared Post (1.91:1)',
                width: 1200,
                height: 627,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-linkedin-company-cover',
                label: 'Company Cover Photo',
                width: 1128,
                height: 191,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-linkedin-background',
                label: 'Profile Background Photo',
                width: 1584,
                height: 396,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-linkedin-profile',
                label: 'Profile Photo (1:1)',
                width: 400,
                height: 400,
                designUnit: 'Pixel',
            },
        ],
    },
    {
        id: 'pinterest',
        title: 'Pinterest',
        presets: [
            {
                id: 'page-sizes-pinterest-standard',
                label: 'Standard Pin (2:3)',
                width: 1000,
                height: 1500,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-pinterest-long',
                label: 'Long Pin',
                width: 1000,
                height: 2100,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-pinterest-profile',
                label: 'Profile Photo (1:1)',
                width: 165,
                height: 165,
                designUnit: 'Pixel',
            },
        ],
    },
    {
        id: 'tiktok',
        title: 'TikTok',
        presets: [
            {
                id: 'page-sizes-tiktok-video',
                label: 'Video (9:16)',
                width: 1080,
                height: 1920,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-tiktok-profile',
                label: 'Profile Photo (1:1)',
                width: 200,
                height: 200,
                designUnit: 'Pixel',
            },
        ],
    },
    {
        id: 'youtube',
        title: 'YouTube',
        presets: [
            {
                id: 'page-sizes-yt-standard',
                label: 'Standard (16:9)',
                width: 1920,
                height: 1080,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-yt-shorts',
                label: 'Shorts (9:16)',
                width: 1080,
                height: 1920,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-yt-profile',
                label: 'Profile Photo (1:1)',
                width: 800,
                height: 800,
                designUnit: 'Pixel',
            },
        ],
    },
    {
        id: 'hd-video',
        title: 'HD Video',
        presets: [
            {
                id: 'page-sizes-hd-480p',
                label: 'SD (480p) (3:2)',
                width: 720,
                height: 480,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-hd-720p',
                label: 'HD (720p) (16:9)',
                width: 1280,
                height: 720,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-hd-1080p',
                label: 'Full HD (1080p) (16:9)',
                width: 1920,
                height: 1080,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-hd-2k',
                label: '2K (17:9)',
                width: 2048,
                height: 1080,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-hd-4k',
                label: '4K (16:9)',
                width: 3840,
                height: 2160,
                designUnit: 'Pixel',
            },
            {
                id: 'page-sizes-hd-cinema-4k',
                label: 'Cinema 4K',
                width: 4096,
                height: 2160,
                designUnit: 'Pixel',
            },
        ],
    },
    {
        id: 'iso-standard-print',
        title: 'ISO Standard Print',
        presets: [
            {
                id: 'print-sizes-din-a0-portrait',
                label: 'DIN A0 Portrait',
                width: 841,
                height: 1189,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a0-landscape',
                label: 'DIN A0 Landscape',
                width: 1189,
                height: 841,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a1-portrait',
                label: 'DIN A1 Portrait',
                width: 594,
                height: 841,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a1-landscape',
                label: 'DIN A1 Landscape',
                width: 841,
                height: 594,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a2-portrait',
                label: 'DIN A2 Portrait',
                width: 420,
                height: 594,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a2-landscape',
                label: 'DIN A2 Landscape',
                width: 594,
                height: 420,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a3-portrait',
                label: 'DIN A3 Portrait',
                width: 297,
                height: 420,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a3-landscape',
                label: 'DIN A3 Landscape',
                width: 420,
                height: 297,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a4-portrait',
                label: 'DIN A4 Portrait',
                width: 210,
                height: 297,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a4-landscape',
                label: 'DIN A4 Landscape',
                width: 297,
                height: 210,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a5-portrait',
                label: 'DIN A5 Portrait',
                width: 148,
                height: 210,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a5-landscape',
                label: 'DIN A5 Landscape',
                width: 210,
                height: 148,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a6-portrait',
                label: 'DIN A6 Portrait',
                width: 105,
                height: 148,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a6-landscape',
                label: 'DIN A6 Landscape',
                width: 148,
                height: 105,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a6-5-portrait',
                label: 'DIN A6/5 Portrait',
                width: 105,
                height: 210,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-a6-5-landscape',
                label: 'DIN A6/5 Landscape',
                width: 210,
                height: 105,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-b5-portrait',
                label: 'DIN B5 Portrait',
                width: 176,
                height: 250,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-din-b5-landscape',
                label: 'DIN B5 Landscape',
                width: 250,
                height: 176,
                designUnit: 'Millimeter',
            },
        ],
    },
    {
        id: 'north-american-print',
        title: 'North American Print',
        presets: [
            {
                id: 'print-sizes-letter-portrait',
                label: 'Letter Portrait',
                width: 8.5,
                height: 11,
                designUnit: 'Inch',
            },
            {
                id: 'print-sizes-letter-landscape',
                label: 'Letter Landscape',
                width: 11,
                height: 8.5,
                designUnit: 'Inch',
            },
            {
                id: 'print-sizes-legal-portrait',
                label: 'Legal Portrait',
                width: 8.5,
                height: 14,
                designUnit: 'Inch',
            },
            {
                id: 'print-sizes-legal-landscape',
                label: 'Legal Landscape',
                width: 14,
                height: 8.5,
                designUnit: 'Inch',
            },
            {
                id: 'print-sizes-tabloid-portrait',
                label: 'Tabloid Portrait',
                width: 11,
                height: 17,
                designUnit: 'Inch',
            },
            {
                id: 'print-sizes-tabloid-landscape',
                label: 'Tabloid Landscape',
                width: 17,
                height: 11,
                designUnit: 'Inch',
            },
        ],
    },
    {
        id: 'other-print',
        title: 'Other Print',
        presets: [
            {
                id: 'print-sizes-postcard-portrait',
                label: 'Postcard Portrait',
                width: 125,
                height: 235,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-postcard-landscape',
                label: 'Postcard Landscape',
                width: 235,
                height: 125,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-business-card-portrait',
                label: 'Business Card Portrait',
                width: 55,
                height: 85,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-business-card-landscape',
                label: 'Business Card Landscape',
                width: 85,
                height: 55,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-poster-portrait',
                label: 'Poster Portrait',
                width: 1000,
                height: 1400,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-poster-landscape',
                label: 'Poster Landscape',
                width: 1400,
                height: 1000,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-flyer-portrait',
                label: 'Flyer Portrait',
                width: 130,
                height: 150,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-flyer-landscape',
                label: 'Flyer Landscape',
                width: 150,
                height: 130,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-brochure-portrait',
                label: 'Brochure Portrait',
                width: 148,
                height: 315,
                designUnit: 'Millimeter',
            },
            {
                id: 'print-sizes-brochure-landscape',
                label: 'Brochure Landscape',
                width: 315,
                height: 148,
                designUnit: 'Millimeter',
            },
        ],
    },
];
