import {
    AnchorIcon,
    ApertureIcon,
    AppleIcon,
    ArchiveIcon,
    BananaIcon,
    BellIcon,
    BirdIcon,
    BookmarkIcon,
    BookOpenIcon,
    BoxIcon,
    BriefcaseIcon,
    BugIcon,
    BuildingIcon,
    CalculatorIcon,
    CalendarIcon,
    CameraIcon,
    CarIcon,
    CarrotIcon,
    CatIcon,
    ChartPieIcon,
    ChefHatIcon,
    CherryIcon,
    ClipboardListIcon,
    ClockIcon,
    CloudSunIcon,
    CodeIcon,
    CoffeeIcon,
    CompassIcon,
    CpuIcon,
    CupSodaIcon,
    DatabaseIcon,
    DiamondIcon,
    DollarSignIcon,
    DropletIcon,
    FilmIcon,
    FishIcon,
    FlagIcon,
    FlameIcon,
    FlaskConicalIcon,
    Gamepad2Icon,
    GemIcon,
    GlassesIcon,
    GlobeIcon,
    GraduationCapIcon,
    HeadphonesIcon,
    HeartIcon,
    HourglassIcon,
    HouseIcon,
    KeyIcon,
    LaptopIcon,
    LandmarkIcon,
    LeafIcon,
    LightbulbIcon,
    ListChecksIcon,
    LockOpenIcon,
    type LucideIcon,
    MailIcon,
    MegaphoneIcon,
    MicroscopeIcon,
    MonitorIcon,
    MoonIcon,
    MountainIcon,
    MusicIcon,
    NewspaperIcon,
    PaletteIcon,
    PaperclipIcon,
    PhoneIcon,
    PinIcon,
    PlaneIcon,
    PlayIcon,
    RadarIcon,
    RocketIcon,
    SailboatIcon,
    ScaleIcon,
    ShieldIcon,
    ShirtIcon,
    ShoppingCartIcon,
    SmileIcon,
    SparklesIcon,
    StarIcon,
    StethoscopeIcon,
    SunIcon,
    SwordIcon,
    TagIcon,
    TentIcon,
    TrainFrontIcon,
    TreePineIcon,
    TrendingUpIcon,
    TrophyIcon,
    TruckIcon,
    UmbrellaIcon,
    UserIcon,
    UtensilsIcon,
    VideoIcon,
    WrenchIcon,
    ZapIcon,
} from 'lucide-react';

/** Keys are persisted on the routine's `icon` column — renaming one silently blanks every routine that picked it. */
export const ROUTINE_ICON_CHOICES: readonly { key: string; Icon: LucideIcon }[] = [
    { key: 'radar', Icon: RadarIcon },
    { key: 'trending-up', Icon: TrendingUpIcon },
    { key: 'newspaper', Icon: NewspaperIcon },
    { key: 'globe', Icon: GlobeIcon },
    { key: 'list-checks', Icon: ListChecksIcon },
    { key: 'lightbulb', Icon: LightbulbIcon },
    { key: 'calendar', Icon: CalendarIcon },
    { key: 'clock', Icon: ClockIcon },
    { key: 'sun', Icon: SunIcon },
    { key: 'moon', Icon: MoonIcon },
    { key: 'cloud-sun', Icon: CloudSunIcon },
    { key: 'coffee', Icon: CoffeeIcon },
    { key: 'bell', Icon: BellIcon },
    { key: 'mail', Icon: MailIcon },
    { key: 'megaphone', Icon: MegaphoneIcon },
    { key: 'chart-pie', Icon: ChartPieIcon },
    { key: 'dollar-sign', Icon: DollarSignIcon },
    { key: 'briefcase', Icon: BriefcaseIcon },
    { key: 'landmark', Icon: LandmarkIcon },
    { key: 'scale', Icon: ScaleIcon },
    { key: 'shopping-cart', Icon: ShoppingCartIcon },
    { key: 'clipboard-list', Icon: ClipboardListIcon },
    { key: 'book-open', Icon: BookOpenIcon },
    { key: 'graduation-cap', Icon: GraduationCapIcon },
    { key: 'microscope', Icon: MicroscopeIcon },
    { key: 'flask-conical', Icon: FlaskConicalIcon },
    { key: 'bug', Icon: BugIcon },
    { key: 'wrench', Icon: WrenchIcon },
    { key: 'rocket', Icon: RocketIcon },
    { key: 'zap', Icon: ZapIcon },
    { key: 'flame', Icon: FlameIcon },
    { key: 'sparkles', Icon: SparklesIcon },
    { key: 'star', Icon: StarIcon },
    { key: 'trophy', Icon: TrophyIcon },
    { key: 'flag', Icon: FlagIcon },
    { key: 'heart', Icon: HeartIcon },
    { key: 'leaf', Icon: LeafIcon },
    { key: 'mountain', Icon: MountainIcon },
    { key: 'compass', Icon: CompassIcon },
    { key: 'plane', Icon: PlaneIcon },
    { key: 'camera', Icon: CameraIcon },
    { key: 'palette', Icon: PaletteIcon },
    { key: 'music', Icon: MusicIcon },
    { key: 'shield', Icon: ShieldIcon },
    { key: 'house', Icon: HouseIcon },
    { key: 'anchor', Icon: AnchorIcon },
    { key: 'aperture', Icon: ApertureIcon },
    { key: 'apple', Icon: AppleIcon },
    { key: 'archive', Icon: ArchiveIcon },
    { key: 'banana', Icon: BananaIcon },
    { key: 'bird', Icon: BirdIcon },
    { key: 'bookmark', Icon: BookmarkIcon },
    { key: 'box', Icon: BoxIcon },
    { key: 'building', Icon: BuildingIcon },
    { key: 'calculator', Icon: CalculatorIcon },
    { key: 'car', Icon: CarIcon },
    { key: 'carrot', Icon: CarrotIcon },
    { key: 'cat', Icon: CatIcon },
    { key: 'chef-hat', Icon: ChefHatIcon },
    { key: 'cherry', Icon: CherryIcon },
    { key: 'code', Icon: CodeIcon },
    { key: 'cpu', Icon: CpuIcon },
    { key: 'cup-soda', Icon: CupSodaIcon },
    { key: 'database', Icon: DatabaseIcon },
    { key: 'diamond', Icon: DiamondIcon },
    { key: 'droplet', Icon: DropletIcon },
    { key: 'film', Icon: FilmIcon },
    { key: 'fish', Icon: FishIcon },
    { key: 'gamepad', Icon: Gamepad2Icon },
    { key: 'gem', Icon: GemIcon },
    { key: 'glasses', Icon: GlassesIcon },
    { key: 'headphones', Icon: HeadphonesIcon },
    { key: 'hourglass', Icon: HourglassIcon },
    { key: 'key', Icon: KeyIcon },
    { key: 'laptop', Icon: LaptopIcon },
    { key: 'lock-open', Icon: LockOpenIcon },
    { key: 'monitor', Icon: MonitorIcon },
    { key: 'paperclip', Icon: PaperclipIcon },
    { key: 'phone', Icon: PhoneIcon },
    { key: 'pin', Icon: PinIcon },
    { key: 'play', Icon: PlayIcon },
    { key: 'sailboat', Icon: SailboatIcon },
    { key: 'shirt', Icon: ShirtIcon },
    { key: 'smile', Icon: SmileIcon },
    { key: 'stethoscope', Icon: StethoscopeIcon },
    { key: 'sword', Icon: SwordIcon },
    { key: 'tag', Icon: TagIcon },
    { key: 'tent', Icon: TentIcon },
    { key: 'train', Icon: TrainFrontIcon },
    { key: 'tree-pine', Icon: TreePineIcon },
    { key: 'truck', Icon: TruckIcon },
    { key: 'umbrella', Icon: UmbrellaIcon },
    { key: 'user', Icon: UserIcon },
    { key: 'utensils', Icon: UtensilsIcon },
    { key: 'video', Icon: VideoIcon },
];

export const routineIconByKey = (key: string | null | undefined): LucideIcon | null =>
    ROUTINE_ICON_CHOICES.find((choice) => choice.key === key)?.Icon ?? null;

/** The picked icon, or the fixed zap default when none is picked. */
export const routineIcon = (iconKey?: string | null): LucideIcon => routineIconByKey(iconKey) ?? ZapIcon;
