import type { LutFilterOption } from './lut-filters';

const categoryFromGroup = (groupId: string) => {
    const parts = groupId.split('/');

    return parts[parts.length - 1] || 'other';
};

export const RAW_LUT_FILTERS: Omit<LutFilterOption, 'dataCy'>[] = [
    {
        id: 'filters.lut/ad1920',
        label: '1920 A.D.',
        category: categoryFromGroup('filters.lut/category/bw'),
        lutUri: '/assets/editor/lut/lut_ad1920_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/bw',
        label: 'Greyed',
        category: categoryFromGroup('filters.lut/category/bw'),
        lutUri: '/assets/editor/lut/lut_bw_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/x400',
        label: 'Dusty',
        category: categoryFromGroup('filters.lut/category/bw'),
        lutUri: '/assets/editor/lut/lut_dusty_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/litho',
        label: 'Litho',
        category: categoryFromGroup('filters.lut/category/bw'),
        lutUri: '/assets/editor/lut/lut_litho_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/sepiahigh',
        label: 'Sepia',
        category: categoryFromGroup('filters.lut/category/bw'),
        lutUri: '/assets/editor/lut/lut_sepia_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/plate',
        label: 'Weathered',
        category: categoryFromGroup('filters.lut/category/bw'),
        lutUri: '/assets/editor/lut/lut_weathered_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/sin',
        label: 'Hard Stuff',
        category: categoryFromGroup('filters.lut/category/bw'),
        lutUri: '/assets/editor/lut/lut_hard_stuff_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/blues',
        label: 'Polaroid',
        category: categoryFromGroup('filters.lut/category/retro'),
        lutUri: '/assets/editor/lut/lut_polaroid_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/front',
        label: 'Sunny 70s',
        category: categoryFromGroup('filters.lut/category/retro'),
        lutUri: '/assets/editor/lut/lut_sunny_70s_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/texas',
        label: 'Oldtimer',
        category: categoryFromGroup('filters.lut/category/retro'),
        lutUri: '/assets/editor/lut/lut_oldtimer_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/celsius',
        label: 'Inferno',
        category: categoryFromGroup('filters.lut/category/retro'),
        lutUri: '/assets/editor/lut/lut_inferno_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/cool',
        label: 'Snappy',
        category: categoryFromGroup('filters.lut/category/retro'),
        lutUri: '/assets/editor/lut/lut_snappy_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/chest',
        label: 'Chestnut',
        category: categoryFromGroup('filters.lut/category/analog'),
        lutUri: '/assets/editor/lut/lut_chestnut_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/winter',
        label: 'Softly',
        category: categoryFromGroup('filters.lut/category/analog'),
        lutUri: '/assets/editor/lut/lut_softly_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/kdynamic',
        label: 'Pebble',
        category: categoryFromGroup('filters.lut/category/analog'),
        lutUri: '/assets/editor/lut/lut_pebble_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/fall',
        label: 'Moss',
        category: categoryFromGroup('filters.lut/category/analog'),
        lutUri: '/assets/editor/lut/lut_moss_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/lenin',
        label: 'Lemon',
        category: categoryFromGroup('filters.lut/category/analog'),
        lutUri: '/assets/editor/lut/lut_lemon_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/pola669',
        label: 'Green Gap',
        category: categoryFromGroup('filters.lut/category/analog'),
        lutUri: '/assets/editor/lut/lut_green_gap_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/elder',
        label: 'Colla',
        category: categoryFromGroup('filters.lut/category/winter'),
        lutUri: '/assets/editor/lut/lut_colla_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/orchid',
        label: 'Solanus',
        category: categoryFromGroup('filters.lut/category/winter'),
        lutUri: '/assets/editor/lut/lut_solanus_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/bleached',
        label: 'Kalmen',
        category: categoryFromGroup('filters.lut/category/winter'),
        lutUri: '/assets/editor/lut/lut_kalmen_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/bleachedblue',
        label: 'Joran',
        category: categoryFromGroup('filters.lut/category/winter'),
        lutUri: '/assets/editor/lut/lut_joran_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/breeze',
        label: 'Levante',
        category: categoryFromGroup('filters.lut/category/winter'),
        lutUri: '/assets/editor/lut/lut_levante_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/blueshadows',
        label: 'Zephyr',
        category: categoryFromGroup('filters.lut/category/winter'),
        lutUri: '/assets/editor/lut/lut_zephyr_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/sunset',
        label: 'Golden',
        category: categoryFromGroup('filters.lut/category/summer'),
        lutUri: '/assets/editor/lut/lut_golden_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/eighties',
        label: 'Low Fire',
        category: categoryFromGroup('filters.lut/category/summer'),
        lutUri: '/assets/editor/lut/lut_low_fire_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/evening',
        label: 'Sunrise',
        category: categoryFromGroup('filters.lut/category/summer'),
        lutUri: '/assets/editor/lut/lut_sunrise_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/k2',
        label: 'Flat Black',
        category: categoryFromGroup('filters.lut/category/summer'),
        lutUri: '/assets/editor/lut/lut_flat_black_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/nogreen',
        label: 'Pumpkin',
        category: categoryFromGroup('filters.lut/category/summer'),
        lutUri: '/assets/editor/lut/lut_pumpkin_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/ancient',
        label: 'Ancient',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_ancient_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/cottoncandy',
        label: 'Candy',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_cottoncandy_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/classic',
        label: 'Classic',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_classic_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/colorful',
        label: 'Colorful',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_colorful_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/creamy',
        label: 'Creamy',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_creamy_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/fixie',
        label: 'Fixie',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_fixie_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/food',
        label: 'Food',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_food_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/fridge',
        label: 'Fridge',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_fridge_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/glam',
        label: 'Glam',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_glam_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/gobblin',
        label: 'Gobblin',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_gobblin_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/highcontrast',
        label: 'Hicon',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_highcontrast_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/highcarb',
        label: 'High Carb',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_highcarb_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/k1',
        label: 'K1',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_k1_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/k6',
        label: 'K6',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_k6_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/keen',
        label: 'Keen',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_keen_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/lomo',
        label: 'Lomo',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_lomo_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/lomo100',
        label: 'Lomo 100',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_lomo100_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/lucid',
        label: 'Lucid',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_lucid_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/mellow',
        label: 'Mellow',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_mellow_8_8_512.png',
        tilesX: 8,
        tilesY: 8,
    },
    {
        id: 'filters.lut/neat',
        label: 'Neat',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_neat_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/pale',
        label: 'Pale',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_pale_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/pitched',
        label: 'Pitched',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_pitched_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/polasx',
        label: 'Pola SX',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_polasx_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/pro400',
        label: 'Pro 400',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_pro400_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/quozi',
        label: 'Quozi',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_quozi_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/settled',
        label: 'Settled',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_settled_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/seventies',
        label: 'Seventies',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_seventies_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/soft',
        label: 'Soft',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_soft_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/steel',
        label: 'Steel',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_steel_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/summer',
        label: 'Summer',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_summer_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/tender',
        label: 'Tender',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_tender_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
    {
        id: 'filters.lut/twilight',
        label: 'Twilight',
        category: categoryFromGroup('filters.lut/category/legacy'),
        lutUri: '/assets/editor/lut/lut_twilight_5_5_128.png',
        tilesX: 5,
        tilesY: 5,
    },
];
